import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex items-center justify-between px-20 text-gray-500 h-20">
        <div className="flex items-center" >
          <Image
            src="/logo 12.png"
            alt="Logo"
            width={180}
            height={10}
            className="mt-2"
          />
        </div>
     
     <div className="flex  items-center justify-center list-none gap-10">
         <li className="hover:text-[#C53030] nav"><Link href='/'>Home</Link></li>
     <li className="hover:text-[#C53030] nav"><Link href='/'>Models</Link></li>
      <li className="hover:text-[#C53030] nav"><Link href='/'>Features</Link></li>
      <li className="hover:text-[#C53030] nav"><Link href='/'>Gallery</Link></li>
      <li className="hover:text-[#C53030] nav"><Link href='/'>Contact</Link></li>
      <li className="bg-[#c53030] text-white py-2 px-5 rounded-lg"><Link href='/'>Build & Price</Link></li>
     </div>
     
      </div>
        {children}
      </body>
    </html>
  );
}
